import type { ProductTemplateWithService } from "@/lib/supabase/queries";

export const STUDENT_ID_CARD_TEMPLATE_ID = "student-id-card-01";

export const STUDENT_ID_CARD_TEMPLATE: ProductTemplateWithService = {
  id: STUDENT_ID_CARD_TEMPLATE_ID,
  service_id: null,
  title: "Student Identity Card",
  slug: STUDENT_ID_CARD_TEMPLATE_ID,
  category: "id-card",
  thumbnail_url: "/template-images/student-id-card.png",
  editable_fields: [
    "school_name",
    "school_subtitle",
    "student_name",
    "student_id",
    "faculty",
    "dob",
    "blood_group",
    "year",
    "address",
    "contact",
    "valid_until",
    "photo"
  ],
  is_featured: true,
  created_at: "2026-05-09T00:00:00.000Z",
  updated_at: "2026-05-09T00:00:00.000Z",
  template_json: {
    width: 340,
    height: 510,
    background: "#0A2463",
    accent: "#E8C84A",
    layers: [
      {
        id: "bg",
        type: "rect",
        name: "Background",
        x: 0,
        y: 0,
        w: 340,
        h: 510,
        fill: "#0A2463",
        stroke: null,
        strokeWidth: 0,
        opacity: 1,
        locked: true,
        visible: true,
        rotation: 0
      },
      {
        id: "header-bg",
        type: "rect",
        name: "Header Background",
        x: 0,
        y: 0,
        w: 340,
        h: 90,
        fill: "#1B3A8C",
        stroke: null,
        strokeWidth: 0,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0
      },
      {
        id: "header-accent",
        type: "rect",
        name: "Header Gold Accent",
        x: 0,
        y: 84,
        w: 340,
        h: 6,
        fill: "#E8C84A",
        stroke: null,
        strokeWidth: 0,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0
      },
      {
        id: "school-name",
        type: "text",
        name: "School Name",
        x: 170,
        y: 35,
        text: "PRINTNEPAL",
        fontSize: 18,
        fontFamily: "Arial, sans-serif",
        fontWeight: "bold",
        fontStyle: "normal",
        fill: "#FFFFFF",
        textAlign: "center",
        letterSpacing: 4,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      },
      {
        id: "school-subtitle",
        type: "text",
        name: "School Subtitle",
        x: 170,
        y: 54,
        text: "INSTITUTE OF TECHNOLOGY",
        fontSize: 9,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#A8C0FF",
        textAlign: "center",
        letterSpacing: 2,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      },
      {
        id: "card-title",
        type: "text",
        name: "Card Title",
        x: 170,
        y: 72,
        text: "STUDENT IDENTITY CARD",
        fontSize: 8,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#E8C84A",
        textAlign: "center",
        letterSpacing: 2,
        opacity: 1,
        locked: true,
        visible: true,
        rotation: 0,
        editable: false
      },
      {
        id: "photo-frame",
        type: "rect",
        name: "Photo Frame",
        x: 20,
        y: 105,
        w: 90,
        h: 110,
        fill: "#1B3A8C",
        stroke: "#E8C84A",
        strokeWidth: 1.5,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0
      },
      {
        id: "photo",
        type: "image",
        name: "Student Photo",
        x: 20,
        y: 105,
        w: 90,
        h: 110,
        src: null,
        placeholder: true,
        clipShape: "rect",
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      },
      {
        id: "label-name",
        type: "text",
        name: "Label: Full Name",
        x: 125,
        y: 118,
        text: "Full Name",
        fontSize: 8,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#A8C0FF",
        textAlign: "left",
        letterSpacing: 0,
        opacity: 1,
        locked: true,
        visible: true,
        rotation: 0,
        editable: false
      },
      {
        id: "student-name",
        type: "text",
        name: "Student Full Name",
        x: 125,
        y: 136,
        text: "John Doe",
        fontSize: 15,
        fontFamily: "Arial, sans-serif",
        fontWeight: "bold",
        fontStyle: "normal",
        fill: "#FFFFFF",
        textAlign: "left",
        letterSpacing: 0,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      },
      {
        id: "label-id",
        type: "text",
        name: "Label: Student ID",
        x: 125,
        y: 158,
        text: "Student ID",
        fontSize: 8,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#A8C0FF",
        textAlign: "left",
        letterSpacing: 0,
        opacity: 1,
        locked: true,
        visible: true,
        rotation: 0,
        editable: false
      },
      {
        id: "student-id",
        type: "text",
        name: "Student ID Number",
        x: 125,
        y: 174,
        text: "2025-0001",
        fontSize: 13,
        fontFamily: "Arial, sans-serif",
        fontWeight: "bold",
        fontStyle: "normal",
        fill: "#E8C84A",
        textAlign: "left",
        letterSpacing: 1,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      },
      {
        id: "label-faculty",
        type: "text",
        name: "Label: Faculty",
        x: 125,
        y: 194,
        text: "Faculty",
        fontSize: 8,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#A8C0FF",
        textAlign: "left",
        letterSpacing: 0,
        opacity: 1,
        locked: true,
        visible: true,
        rotation: 0,
        editable: false
      },
      {
        id: "faculty",
        type: "text",
        name: "Faculty / Department",
        x: 125,
        y: 210,
        text: "Computer Science",
        fontSize: 11,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#FFFFFF",
        textAlign: "left",
        letterSpacing: 0,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      },
      {
        id: "divider-1",
        type: "rect",
        name: "Divider 1",
        x: 20,
        y: 228,
        w: 300,
        h: 1,
        fill: "#1B3A8C",
        stroke: null,
        strokeWidth: 0,
        opacity: 1,
        locked: true,
        visible: true,
        rotation: 0
      },
      {
        id: "label-dob",
        type: "text",
        name: "Label: Date of Birth",
        x: 20,
        y: 248,
        text: "Date of Birth",
        fontSize: 8,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#A8C0FF",
        textAlign: "left",
        letterSpacing: 0,
        opacity: 1,
        locked: true,
        visible: true,
        rotation: 0,
        editable: false
      },
      {
        id: "dob",
        type: "text",
        name: "Date of Birth",
        x: 20,
        y: 262,
        text: "01 Jan 2000",
        fontSize: 10,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#FFFFFF",
        textAlign: "left",
        letterSpacing: 0,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      },
      {
        id: "label-blood",
        type: "text",
        name: "Label: Blood Group",
        x: 140,
        y: 248,
        text: "Blood Group",
        fontSize: 8,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#A8C0FF",
        textAlign: "left",
        letterSpacing: 0,
        opacity: 1,
        locked: true,
        visible: true,
        rotation: 0,
        editable: false
      },
      {
        id: "blood-group",
        type: "text",
        name: "Blood Group",
        x: 140,
        y: 262,
        text: "B+",
        fontSize: 10,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#FFFFFF",
        textAlign: "left",
        letterSpacing: 0,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      },
      {
        id: "label-year",
        type: "text",
        name: "Label: Year",
        x: 240,
        y: 248,
        text: "Year",
        fontSize: 8,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#A8C0FF",
        textAlign: "left",
        letterSpacing: 0,
        opacity: 1,
        locked: true,
        visible: true,
        rotation: 0,
        editable: false
      },
      {
        id: "year",
        type: "text",
        name: "Academic Year",
        x: 240,
        y: 262,
        text: "2nd Year",
        fontSize: 10,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#FFFFFF",
        textAlign: "left",
        letterSpacing: 0,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      },
      {
        id: "divider-2",
        type: "rect",
        name: "Divider 2",
        x: 20,
        y: 276,
        w: 300,
        h: 1,
        fill: "#1B3A8C",
        stroke: null,
        strokeWidth: 0,
        opacity: 1,
        locked: true,
        visible: true,
        rotation: 0
      },
      {
        id: "label-address",
        type: "text",
        name: "Label: Address",
        x: 20,
        y: 296,
        text: "Address",
        fontSize: 8,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#A8C0FF",
        textAlign: "left",
        letterSpacing: 0,
        opacity: 1,
        locked: true,
        visible: true,
        rotation: 0,
        editable: false
      },
      {
        id: "address",
        type: "text",
        name: "Address",
        x: 20,
        y: 310,
        text: "Kathmandu, Nepal",
        fontSize: 10,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#FFFFFF",
        textAlign: "left",
        letterSpacing: 0,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      },
      {
        id: "label-contact",
        type: "text",
        name: "Label: Contact",
        x: 20,
        y: 330,
        text: "Contact",
        fontSize: 8,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#A8C0FF",
        textAlign: "left",
        letterSpacing: 0,
        opacity: 1,
        locked: true,
        visible: true,
        rotation: 0,
        editable: false
      },
      {
        id: "contact",
        type: "text",
        name: "Contact Number",
        x: 20,
        y: 344,
        text: "+977-9800000000",
        fontSize: 10,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#FFFFFF",
        textAlign: "left",
        letterSpacing: 0,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      },
      {
        id: "label-valid",
        type: "text",
        name: "Label: Valid Until",
        x: 20,
        y: 368,
        text: "Valid Until",
        fontSize: 8,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#A8C0FF",
        textAlign: "left",
        letterSpacing: 0,
        opacity: 1,
        locked: true,
        visible: true,
        rotation: 0,
        editable: false
      },
      {
        id: "valid-until",
        type: "text",
        name: "Valid Until Date",
        x: 20,
        y: 382,
        text: "Dec 2026",
        fontSize: 10,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#E8C84A",
        textAlign: "left",
        letterSpacing: 0,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      },
      {
        id: "divider-gold",
        type: "rect",
        name: "Gold Divider",
        x: 20,
        y: 400,
        w: 300,
        h: 1,
        fill: "#E8C84A",
        stroke: null,
        strokeWidth: 0,
        opacity: 1,
        locked: true,
        visible: true,
        rotation: 0
      },
      {
        id: "signature-box",
        type: "rect",
        name: "Signature Box",
        x: 20,
        y: 415,
        w: 90,
        h: 36,
        fill: "#1B3A8C",
        stroke: "#A8C0FF",
        strokeWidth: 0.5,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0
      },
      {
        id: "signature-label",
        type: "text",
        name: "Signature Label",
        x: 65,
        y: 440,
        text: "Signature",
        fontSize: 7,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#A8C0FF",
        textAlign: "center",
        letterSpacing: 0,
        opacity: 1,
        locked: true,
        visible: true,
        rotation: 0,
        editable: false
      },
      {
        id: "seal-label",
        type: "text",
        name: "Principal Seal Label",
        x: 240,
        y: 428,
        text: "Principal's Seal",
        fontSize: 7,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#A8C0FF",
        textAlign: "center",
        letterSpacing: 0,
        opacity: 1,
        locked: true,
        visible: true,
        rotation: 0,
        editable: false
      },
      {
        id: "seal-circle",
        type: "ellipse",
        name: "Seal Circle",
        x: 218,
        y: 432,
        w: 44,
        h: 44,
        fill: "transparent",
        stroke: "#1B3A8C",
        strokeWidth: 1,
        opacity: 1,
        locked: true,
        visible: true,
        rotation: 0
      },
      {
        id: "footer-bar",
        type: "rect",
        name: "Footer Bar",
        x: 0,
        y: 490,
        w: 340,
        h: 20,
        fill: "#E8C84A",
        stroke: null,
        strokeWidth: 0,
        opacity: 1,
        locked: true,
        visible: true,
        rotation: 0
      },
      {
        id: "footer-text",
        type: "text",
        name: "Footer Text",
        x: 170,
        y: 504,
        text: "IF FOUND PLEASE RETURN TO SCHOOL OFFICE",
        fontSize: 7,
        fontFamily: "Arial, sans-serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#0A2463",
        textAlign: "center",
        letterSpacing: 1,
        opacity: 1,
        locked: true,
        visible: true,
        rotation: 0,
        editable: true
      }
    ]
  }
};
