import type { ProductTemplateWithService } from "@/lib/supabase/queries";

export const WEDDING_CARD_TEMPLATE_ID = "wedding-card-01";

export const WEDDING_CARD_TEMPLATE: ProductTemplateWithService = {
  id: WEDDING_CARD_TEMPLATE_ID,
  service_id: null,
  title: "Wedding Invitation Card",
  slug: WEDDING_CARD_TEMPLATE_ID,
  category: "wedding",
  thumbnail_url: "/template-images/wedding-card.png",
  editable_fields: ["tagline", "photo", "name_bride", "name_groom", "date", "time", "venue", "rsvp"],
  is_featured: true,
  created_at: "2026-05-09T00:00:00.000Z",
  updated_at: "2026-05-09T00:00:00.000Z",
  template_json: {
    width: 500,
    height: 700,
    background: "#FDF6EC",
    accent: "#C9A96E",
    layers: [
      {
        id: "bg",
        type: "rect",
        name: "Background",
        x: 0,
        y: 0,
        w: 500,
        h: 700,
        fill: "#FDF6EC",
        stroke: null,
        strokeWidth: 0,
        opacity: 1,
        locked: true,
        visible: true,
        rotation: 0
      },
      {
        id: "border-outer",
        type: "rect",
        name: "Outer Border",
        x: 14,
        y: 14,
        w: 472,
        h: 672,
        fill: "transparent",
        stroke: "#C9A96E",
        strokeWidth: 2,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0
      },
      {
        id: "border-inner",
        type: "rect",
        name: "Inner Border",
        x: 22,
        y: 22,
        w: 456,
        h: 656,
        fill: "transparent",
        stroke: "#C9A96E",
        strokeWidth: 0.8,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0
      },
      {
        id: "deco-top",
        type: "rect",
        name: "Top Divider Bar",
        x: 50,
        y: 52,
        w: 400,
        h: 2,
        fill: "#C9A96E",
        stroke: null,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0
      },
      {
        id: "deco-bottom",
        type: "rect",
        name: "Bottom Divider Bar",
        x: 50,
        y: 646,
        w: 400,
        h: 2,
        fill: "#C9A96E",
        stroke: null,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0
      },
      {
        id: "corner-tl",
        type: "ellipse",
        name: "Corner Floral TL",
        x: 14,
        y: 14,
        w: 44,
        h: 44,
        fill: "#E8D5B0",
        stroke: "#C9A96E",
        strokeWidth: 1,
        opacity: 0.7,
        locked: false,
        visible: true,
        rotation: 0
      },
      {
        id: "corner-tr",
        type: "ellipse",
        name: "Corner Floral TR",
        x: 442,
        y: 14,
        w: 44,
        h: 44,
        fill: "#E8D5B0",
        stroke: "#C9A96E",
        strokeWidth: 1,
        opacity: 0.7,
        locked: false,
        visible: true,
        rotation: 0
      },
      {
        id: "corner-bl",
        type: "ellipse",
        name: "Corner Floral BL",
        x: 14,
        y: 642,
        w: 44,
        h: 44,
        fill: "#E8D5B0",
        stroke: "#C9A96E",
        strokeWidth: 1,
        opacity: 0.7,
        locked: false,
        visible: true,
        rotation: 0
      },
      {
        id: "corner-br",
        type: "ellipse",
        name: "Corner Floral BR",
        x: 442,
        y: 642,
        w: 44,
        h: 44,
        fill: "#E8D5B0",
        stroke: "#C9A96E",
        strokeWidth: 1,
        opacity: 0.7,
        locked: false,
        visible: true,
        rotation: 0
      },
      {
        id: "tagline",
        type: "text",
        name: "Tagline",
        x: 250,
        y: 115,
        text: "TOGETHER FOREVER",
        fontSize: 13,
        fontFamily: "Georgia, serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#B8960C",
        textAlign: "center",
        letterSpacing: 5,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      },
      {
        id: "photo-frame",
        type: "ellipse",
        name: "Couple Photo Frame",
        x: 150,
        y: 145,
        w: 200,
        h: 200,
        fill: "#EDE0C8",
        stroke: "#C9A96E",
        strokeWidth: 1.5,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0
      },
      {
        id: "photo",
        type: "image",
        name: "Couple Photo",
        x: 150,
        y: 145,
        w: 200,
        h: 200,
        src: null,
        placeholder: true,
        clipShape: "ellipse",
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      },
      {
        id: "name-bride",
        type: "text",
        name: "Bride Name",
        x: 250,
        y: 390,
        text: "Priya",
        fontSize: 34,
        fontFamily: "Georgia, serif",
        fontWeight: "normal",
        fontStyle: "italic",
        fill: "#8B6508",
        textAlign: "center",
        letterSpacing: 1,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      },
      {
        id: "ampersand",
        type: "text",
        name: "Ampersand",
        x: 250,
        y: 422,
        text: "&",
        fontSize: 20,
        fontFamily: "Georgia, serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#C9A96E",
        textAlign: "center",
        letterSpacing: 0,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: false
      },
      {
        id: "name-groom",
        type: "text",
        name: "Groom Name",
        x: 250,
        y: 460,
        text: "Rahul",
        fontSize: 34,
        fontFamily: "Georgia, serif",
        fontWeight: "normal",
        fontStyle: "italic",
        fill: "#8B6508",
        textAlign: "center",
        letterSpacing: 1,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      },
      {
        id: "invite-text",
        type: "text",
        name: "Invite Message",
        x: 250,
        y: 498,
        text: "REQUEST THE HONOUR OF YOUR PRESENCE",
        fontSize: 11,
        fontFamily: "Georgia, serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#7A6040",
        textAlign: "center",
        letterSpacing: 2,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      },
      {
        id: "date",
        type: "text",
        name: "Wedding Date",
        x: 250,
        y: 530,
        text: "Saturday, 14th June 2025",
        fontSize: 22,
        fontFamily: "Georgia, serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#8B6508",
        textAlign: "center",
        letterSpacing: 0,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      },
      {
        id: "time",
        type: "text",
        name: "Wedding Time",
        x: 250,
        y: 558,
        text: "6:00 PM onwards",
        fontSize: 12,
        fontFamily: "Georgia, serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#7A6040",
        textAlign: "center",
        letterSpacing: 0,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      },
      {
        id: "venue",
        type: "text",
        name: "Venue",
        x: 250,
        y: 580,
        text: "The Grand Ballroom, Kathmandu",
        fontSize: 12,
        fontFamily: "Georgia, serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#7A6040",
        textAlign: "center",
        letterSpacing: 0,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      },
      {
        id: "rsvp",
        type: "text",
        name: "RSVP",
        x: 250,
        y: 622,
        text: "RSVP: +977-9800000000",
        fontSize: 10,
        fontFamily: "Georgia, serif",
        fontWeight: "normal",
        fontStyle: "normal",
        fill: "#B8960C",
        textAlign: "center",
        letterSpacing: 3,
        opacity: 1,
        locked: false,
        visible: true,
        rotation: 0,
        editable: true
      }
    ]
  },
  services: {
    title: "Wedding Invitation Card",
    slug: "wedding-catalogs-cards",
    category: "wedding"
  }
};
